// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciTakipSistemi.Models;

namespace OgrenciTakipSistemi.Migrations
{
    [DbContext(typeof(OkulContext))]
    partial class OkulContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Klup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kontenjan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Klupler");
                });

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Not", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<double>("Ortalama")
                        .HasColumnType("float");

                    b.Property<int>("Proje")
                        .HasColumnType("int");

                    b.Property<int>("Sınav1")
                        .HasColumnType("int");

                    b.Property<int>("Sınav2")
                        .HasColumnType("int");

                    b.Property<int>("Sınav3")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Notlar");
                });

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlupId")
                        .HasColumnType("int");

                    b.Property<string>("SoyIsim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlupId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Not", b =>
                {
                    b.HasOne("OgrenciTakipSistemi.Models.Ders", "Ders")
                        .WithMany("Not")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciTakipSistemi.Models.Ogrenci", "Ogrenci")
                        .WithMany("Not")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Ogrenci", b =>
                {
                    b.HasOne("OgrenciTakipSistemi.Models.Klup", "Klup")
                        .WithMany("Ogrenci")
                        .HasForeignKey("KlupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klup");
                });

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Ders", b =>
                {
                    b.Navigation("Not");
                });

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Klup", b =>
                {
                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciTakipSistemi.Models.Ogrenci", b =>
                {
                    b.Navigation("Not");
                });
#pragma warning restore 612, 618
        }
    }
}
